### ISSUE TITLE
Incorrect results from report

### ISSUE THREAD

**Issue by sataris** [Magicalex/rtorrent-cleaner#3]
Hi there, 

This software looks awesome, but I'm running into an issue with the report. 

Under 'X Files not tracked by Rtorrent' it returns. 

` 44  │ /My/Path/CD2/06 Poseidon.flac           │ 53.19Mo`

Then under 'X' Files are missing' it returns

`2  │ /My/Path//CD2/06 Poseidon.flac          │ 53.19Mo`

*Note the // in the 2nd path. 

An item shouldn't be 'Not Tracked By Rtorrent' at the same time it's under 'Files are missing'. 

Which leads to the 3rd issue. 

The file is in Rtorrent anyway.

![image](https://user-images.githubusercontent.com/1229458/65352782-0a36bd80-dc1e-11e9-9e6f-a2840528c1f8.png)

**Comment by al3xLvs** [comment]
This path is weird `/My/Path//CD2/06 Poseidon.flac`

You use rtorrent-cleaner version 0.9.0? check with this cmd `rtorrent-cleaner -V`

**Comment by sataris** [comment]
Yeah I'm using v.0.9.0 

If I get the chance, I may have a play around and see if I can find the issue.

**Comment by al3xLvs** [comment]
@sataris do you have still the same problem with the version 0.9.1?

**Comment by sataris** [comment]
@Magicalex 

Sorry for the late reply, I just tried this again with 0.9.1 and the issue still remains.

**Comment by al3xLvs** [comment]
@sataris Hi!

Can you execute this php file for test your torrent? I need more information.
https://gist.github.com/Magicalex/559e492f2dd56a73dc937a8422874855

```
wget https://gist.githubusercontent.com/Magicalex/559e492f2dd56a73dc937a8422874855/raw/964b3ec1fbcb51277e1910ecd06772ce7af5edbb/test%2520rtorrent-cleaner -O test.php
vi test.php
```

You need to change `$scgi`, `$port` and `$hash` var. [here](https://gist.github.com/Magicalex/559e492f2dd56a73dc937a8422874855#file-test-rtorrent-cleaner-L8-L10)
You need to find the hash of the torrent in rutorrent or rtorrent.
(like `00DC3081C0870A26EC58CA224D267CF68881E64B`)

Save and run the file.
```sh
php test.php
```

**Comment by al3xLvs** [comment]
@sataris Hi! I made a lot of changes, I released version 0.9.4.

Can you stop and start the torrent, and try again with version 0.9.4 of rtorrent-cleaner?

**Comment by sataris** [comment]
I just tried this with 0.9.4 and it seems to better, 

~~The path still seem quite off though,~~ 

~~For example.~~ 

~~`/my/path/music/somefile/disc.inf  `~~

~~is what is reported, but the path on disk is and in rtorrent is~~

~~'/my/path/movies/somefile/disc.inf  '~~

EDIT: This was working correctly, and the path was indeed duplicated! :)

Also, I did note that now I have 2 files under 'Files are missing' 

`[ Disc 1/06 - Telephone (feat. Beyonc?).mp3 ]`
`Disc 1/06 - Telephone (feat. Beyonc?).flac `
This may be because of the '?' in the path. 

But it does seem like it's way more accurate than before.

**Comment by sataris** [comment]
Just as an update to this, 

I had a play around, and one of the reasons, seems to be caused by rtorrentFileData[] returning URL's with //

I've gotten around this is in my fork, with replacing 

```php
$this->rtorrentFileData[] = [
    'absolute_path' => $path,
    'size'          => (int) $file[2]
];

$this->rtorrentFileData[] = [
    'absolute_path' => preg_replace('#/+#', '/', $path),
    'size'          => (int) $file[2]
];
```

This strips out any multiple forward slashes from the path, and it does seem to work. 

The encoding around the ? is still an issue though.

**Comment by sataris** [comment]
After way more research, 

I'm pretty happy with the result of removing the // from the rtorrentFileData. it seems to work fine, and the list is more accurate. 

The ? is still problematic, most likely coming from an encoding that's not expected.

ls -al  shows the file on disk as 

c'$'\351'').mp3'

however file_exists, will never return true as it's running through as 

c�).mp3

I've tried through several different encodings to try to find the culprit. with no luck  Argh!

**Comment by al3xLvs** [comment]
Have you set the correct encoding in your rtorrent.rc?

```
encoding.add = UTF-8
```

**Comment by sataris** [comment]
Yeah, It seems to be something wrong either my shell or my server, 

Don't think its an issue with the script, 

Do you want a PR for the double // though?

**Comment by al3xLvs** [comment]
@sataris Can you try to fix your shell before?
Maybe double slash issue is the same problem.

**Comment by al3xLvs** [comment]
@sataris any news about your shell?
